### ISSUE TITLE
피드 작성하기

### ISSUE THREAD

**Issue by Yeonwoo-Ga** [Hanghae99-DoBlock/FE#45]

**Comment by Yeonwoo-Ga** [comment]
feed 폴더와 feedSlice 위주로 봐주시면 됩니다!

**Comment by NyeongDev** [comment]
- 아래 코드들은 사용되지 않는 코드인 것 같은데 맞을까요? 맞다면 지워주시면 좋을 것 같아요~!
https://github.com/Hanghae99-DoBlock/FE/blob/82e9035a1863ece5679187ba94b87a199a511f71/src/pages/feed/ChoiceTodoModal.jsx#L5
https://github.com/Hanghae99-DoBlock/FE/blob/82e9035a1863ece5679187ba94b87a199a511f71/src/pages/feed/ChoiceTodoModal.jsx#L15
https://github.com/Hanghae99-DoBlock/FE/blob/82e9035a1863ece5679187ba94b87a199a511f71/src/pages/feed/AddFeedPage.jsx#L18


https://github.com/Hanghae99-DoBlock/FE/blob/82e9035a1863ece5679187ba94b87a199a511f71/src/pages/feed/ChoiceTodoModal.jsx#L13



여기도 사용되지 않는 코드인 것 같은데 맞을까요?

https://github.com/Hanghae99-DoBlock/FE/blob/82e9035a1863ece5679187ba94b87a199a511f71/src/pages/feed/ChoiceTodoModal.jsx#L62
인풋은 컴포넌트 분리해주시면 좋을 것 같아요!

- 콘솔로그는 커밋 전에 지우셨는지 한번 확인해주세용
https://github.com/Hanghae99-DoBlock/FE/blob/82e9035a1863ece5679187ba94b87a199a511f71/src/pages/feed/ChoiceTodo.jsx#L17

- AddFeedPage.jsx 안에서 button, textarea 스타일 컴포넌트 사용하고 계신 것 같은데 common 폴더에 있는 컴포넌트 사용해주시면 좋을 것 같아요~

- pages 폴더 안에 페이지뿐만 아니라 컴포넌트도 같이 들어있는 것 같아요! 컴포넌트는 컴포넌트 폴더로 옮겨주시면 좋을 것 같습니다~

- 다음 코드 리뷰 때는 코드에 주석 달아주시면 좋을 것 같아요~!
- 커밋 메시지에도 작업 내용 자세하게 적어주시면 좋을 것 같아요~!

https://github.com/Hanghae99-DoBlock/FE/blob/82e9035a1863ece5679187ba94b87a199a511f71/src/pages/feed/ChoiceTodoModal.jsx#L52
FeedPage를 map 돌리는 이유가 무엇인가요?
