### ISSUE TITLE
팔로워/팔로잉 리스트 조회 페이지

### ISSUE THREAD

**Issue by ose1012** [Hanghae99-DoBlock/FE#51]

**Comment by NyeongDev** [comment]
성은님 고생하셨습니다 :) !! 👍 주석 자세히 달아주셔서 읽기 좋았습니다~!

### 컨벤션, 가독성 관련

- 인라인 스타일이 남아있는 부분이 있어요
- 대문자로 시작하는 변수명이 있어요
- 콘솔 로그도 남아있는지 한번 확인해주시면 좋을 것 같아요
- 변수 이름이 좀 더 명시적이었으면 좋을 것 같아요! isBlue, changeBlue 처럼 어떤 색으로 바뀌는지보다는 어떤 역할을 수행하는지가 보이면 더 가독성이 좋아질 것 같습니다!

### 기능 관련
- window.history.back이 모바일에서도 작동하는지 궁금합니다!

**Comment by ose1012** [comment]
확인 감사합니다 민영님!! 말씀해주신 부분들 확인 후 수정하도록 하겠습니다^^> 기능 관련해서 window.history.back 부분은 모바일 환경에서도 작동하는지 테스트 해보지 않아서 확인 후 답변 드리도록 하겠습니다!
